import Link from 'next/link';
import './globals.css'
import style from "./page.module.css";
import LoginButton from '@/components/Button/LoginButton';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions);
  console.log(session);
  if(session){

  }
  return (
    <html lang="en">

      <body >
        <div className={style.headerNav}>
          <div className={style.navItem}>
            <Link href={"/"}>Abidos</Link>
          </div>
          <div className={style.navItem}>
            <Link href={"/list"}>List</Link>
          </div>
          <div className={style.navItem}>
            <Link href={"/write"}>Write</Link>
          </div>
          <div className={style.right}>
            {!session &&
            <div className={style.navItem}>
              <LoginButton></LoginButton>
            </div>
            }
            {
              session &&
              <h4>Wellcome {session.user.name}</h4>
            }
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
